services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - network
networks:
  network:
